--
-- Task:  It would be useful to know when reviews were recorded. So, write a
--        SQL statement to alter the reviews table to add a 'review_date'
--        column which should take a 'date' data type.
--
